CREATE DATABASE IF NOT EXISTS restaurant_project;
USE restaurant_project;

CREATE TABLE IF NOT EXISTS dishes (
    id        INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name      VARCHAR(255) NOT NULL,
    frequency INT          NOT NULL DEFAULT 1
);

-- Seed 300+ common dishes with realistic frequencies.
-- The engine will also fall back to data/dataset.txt (1000 entries)
-- when this table is empty or DB is unavailable.
INSERT IGNORE INTO dishes (name, frequency) VALUES
('pasta carbonara', 95),('spaghetti bolognese', 98),('fettuccine alfredo', 90),
('lasagna bolognese', 88),('penne arrabbiata', 82),('rigatoni amatriciana', 75),
('linguine alle vongole', 78),('tagliatelle al ragu', 80),('spaghetti aglio olio', 85),
('bucatini cacio pepe', 79),('pasta puttanesca', 72),('gnocchi al pesto', 83),
('ravioli ricotta spinaci', 76),('tortellini panna prosciutto', 70),
('pizza margherita', 99),('pizza napoletana', 96),('pizza quattro stagioni', 84),
('pizza diavola', 87),('pizza capricciosa', 81),('pizza quattro formaggi', 86),
('pizza marinara', 75),('pepperoni pizza', 97),('four cheese pizza', 91),
('mushroom pizza', 83),('bbq chicken pizza', 88),('buffalo chicken pizza', 85),
('calzone classico', 74),
('risotto ai funghi', 86),('risotto alla milanese', 84),('risotto al nero di seppia', 70),
('risotto ai gamberetti', 75),('risotto primavera', 68),
('osso buco alla milanese', 72),('pollo alla cacciatora', 74),
('bistecca alla fiorentina', 88),('cotoletta alla milanese', 82),('vitello tonnato', 70),
('polpette al sugo', 73),('bruschetta al pomodoro', 90),('arancini di riso', 85),
('focaccia genovese', 80),('focaccia rosmarino', 77),
('tiramisu', 99),('panna cotta', 96),('cannoli siciliani', 88),
('gelato cioccolato', 94),('gelato fragola', 90),('gelato pistacchio', 89),
('gelato limone', 86),('granita limone', 78),
('prosciutto crudo', 92),('burrata pugliese', 91),('mozzarella di bufala', 93),
('parmigiano reggiano', 88),('gorgonzola dolce', 79),('affogato al caffe', 85),
('croissant beurre', 96),('pain au chocolat', 94),('baguette tradition', 92),
('quiche lorraine', 90),('crepe complete jambon', 84),('croque monsieur', 91),
('croque madame', 88),('bouillabaisse marseillaise', 75),('boeuf bourguignon', 88),
('coq au vin', 86),('confit de canard', 82),('ratatouille provencale', 83),
('salade nicoise', 84),('moules mariniere', 82),('steak tartare', 85),
('creme brulee', 97),('mousse au chocolat', 93),('mille-feuille', 88),
('eclair au chocolat', 92),('macaron parisien', 95),('tarte tatin', 86),
('profiteroles', 89),
('cheeseburger classic', 98),('double cheeseburger', 96),('bacon cheeseburger', 95),
('veggie burger', 88),('chicken burger', 92),('fish burger crispy', 85),
('hot dog chicago style', 90),('mac and cheese', 97),('grilled cheese sandwich', 93),
('club sandwich', 91),('blt sandwich', 89),('pulled pork sandwich', 86),
('philly cheesesteak', 92),('reuben sandwich', 88),('lobster roll', 85),
('new england clam chowder', 87),('chicken pot pie', 84),('beef stew hearty', 80),
('chicken wings classic', 97),('buffalo wings', 95),('bbq ribs slow cooked', 93),
('pulled pork barbecue', 90),('fried chicken southern', 96),('crab cakes maryland', 84),
('shrimp and grits', 82),('caesar salad', 95),('cobb salad', 88),
('french fries', 99),('onion rings', 91),('nachos loaded', 93),
('apple pie american', 94),('cheesecake new york', 96),('red velvet cake', 91),
('banana split', 88),('chocolate milkshake', 93),
('pancakes buttermilk', 92),('belgian waffles', 90),('eggs benedict', 93),
('sushi nigiri', 97),('sushi maki roll', 95),('sashimi salmon', 94),
('sashimi tuna', 92),('ramen tonkotsu', 98),('ramen shoyu', 93),('ramen miso', 95),
('udon tempura', 86),('soba noodles cold', 83),('tempura shrimp', 90),
('tonkatsu pork cutlet', 92),('katsu curry', 94),('chicken katsu', 91),
('gyudon beef rice bowl', 87),('karaage chicken', 93),('yakitori grilled skewers', 90),
('teriyaki chicken', 96),('teriyaki salmon', 91),('gyoza pan fried', 94),
('takoyaki octopus balls', 88),('okonomiyaki osaka', 85),('yakisoba stir fried', 86),
('miso soup tofu', 90),('edamame salted', 93),('mochi ice cream', 91),
('matcha ice cream', 89),('daifuku mochi', 86),
('dim sum assorted', 92),('har gow shrimp dumpling', 90),('siu mai pork dumpling', 89),
('spring roll crispy', 91),('fried rice yangzhou', 90),('egg fried rice', 93),
('lo mein soft noodles', 87),('chow mein crispy noodles', 88),
('wonton soup', 88),('mapo tofu', 88),('kung pao chicken', 94),
('orange chicken', 95),('general tso chicken', 93),('sweet and sour pork', 90),
('char siu pork', 87),('peking duck', 93),
('butter chicken', 99),('chicken tikka masala', 98),('chicken biryani', 97),
('lamb biryani', 94),('vegetable biryani', 88),('lamb korma', 85),
('chicken korma', 87),('chicken vindaloo', 82),('lamb rogan josh', 84),
('dal makhani', 90),('chana masala', 88),('palak paneer', 92),
('paneer tikka', 90),('aloo gobi', 85),('baingan bharta', 80),('mutter paneer', 83),
('naan bread', 96),('garlic naan', 97),('paratha whole wheat', 85),
('samosa vegetable', 91),('onion bhaji', 88),('dosa crispy', 87),('masala dosa', 89),
('chole bhature', 84),('pani puri', 88),('gulab jamun', 93),
('kheer rice pudding', 85),('kulfi mango', 87),('mango lassi', 95),('chai masala', 96),
('tacos al pastor', 97),('tacos carne asada', 95),('fish tacos baja', 90),
('shrimp tacos', 88),('burrito carne asada', 92),('enchiladas rojas', 88),
('enchiladas verdes', 86),('pozole rojo', 80),('chiles rellenos', 78),
('mole negro oaxaca', 76),('cochinita pibil', 80),('carnitas crispy', 85),
('barbacoa beef', 83),('birria tacos', 90),('quesadilla cheese', 93),
('huevos rancheros', 85),('chilaquiles rojos', 82),
('flan caramel', 88),('tres leches cake', 90),('churros cinnamon', 92),
('guacamole fresh', 96),('pico de gallo', 92),('salsa verde tomatillo', 88),
('pad thai classic', 98),('pad see ew', 90),('pad kra pao basil', 88),
('massaman curry beef', 87),('green curry chicken', 92),('red curry shrimp', 90),
('yellow curry vegetable', 86),('tom yum soup shrimp', 91),('tom kha gai coconut', 89),
('mango sticky rice', 93),('som tum papaya salad', 85),
('hummus classic', 96),('baba ganoush', 90),('tabbouleh parsley', 88),
('falafel crispy', 94),('shawarma chicken', 96),('shawarma lamb', 92),
('kebab grilled', 90),('shakshuka eggs', 91),('tzatziki yogurt dip', 88),
('spanakopita spinach pie', 83),('baklava honey walnut', 91),
('moussaka eggplant', 87),('souvlaki pork skewer', 88),('gyros pita', 92),
('greek salad horiatiki', 90),('avgolemono egg lemon soup', 78),
('paella valenciana', 94),('seafood paella', 92),('tortilla espanola', 88),
('patatas bravas', 90),('gambas al ajillo', 87),('gazpacho andaluz', 86),
('jamon iberico', 91),('churros con chocolate', 90),('crema catalana', 87),
('bratwurst grilled', 88),('wiener schnitzel', 90),('pretzel soft baked', 85),
('black forest cake', 88),('strudel apple', 84),
('bibimbap korean', 95),('japchae glass noodles', 88),
('tteokbokki spicy rice cakes', 90),('kimchi fried rice', 93),
('bulgogi grilled beef', 94),('samgyeopsal pork belly', 91),
('kimchi jjigae kimchi stew', 88),('kimbap rice roll', 87),
('pho bo beef noodle', 97),('pho ga chicken noodle', 94),('bun bo hue spicy beef', 88),
('bun cha grilled pork', 86),('banh mi vietnamese sandwich', 92),
('goi cuon fresh spring roll', 84),
('ribeye steak', 96),('filet mignon', 95),('t-bone steak', 91),
('sirloin steak', 90),('wagyu beef sirloin', 88),('prime rib au jus', 85),
('rack of lamb', 84),('pork chops', 85),('grilled chicken breast', 94),
('grilled lobster', 87),('shrimp scampi', 88),('grilled shrimp', 87),
('mussels marinara', 85),('fish and chips', 91),('grilled salmon', 92),
('pan seared scallops', 86),('calamari fritti', 88),
('avocado toast', 94),('acai bowl', 88),('granola yogurt bowl', 85),
('caprese salad', 91),('cobb salad', 88),('burrata caprese', 87),
('charcuterie board', 90),('french onion soup', 88),('lobster bisque', 85),
('mushroom cream soup', 82),('minestrone soup', 85),('tortilla soup', 86),
('espresso double', 97),('cappuccino', 98),('latte caffe', 96),
('macchiato espresso', 91),('flat white', 89),('mocha chocolate', 92),
('iced coffee', 94),('cold brew coffee', 90),('matcha latte', 93),
('chai latte', 92),('hot chocolate', 96),('mango smoothie', 88),
('chocolate lava cake', 93),('brownie fudge', 90),('carrot cake cream cheese', 88),
('strawberry cheesecake', 92),('lemon tart', 88),('eclairs chocolate', 89),
('vanilla ice cream', 96),('chocolate ice cream', 95),('mango sorbet', 86),
('chocolate gelato', 90),('hazelnut gelato', 87),
('poke bowl tuna', 92),('ceviche lime', 88),('buddha bowl grain', 85),
('spicy tuna roll', 92),('california roll', 90),
('chicken marsala', 88),('chicken piccata', 86),('chicken parmigiana', 92),
('shrimp fettuccine', 87),('seafood linguine', 85),
('surf and turf', 88),('truffle pasta', 86),
('gumbo louisiana', 85),('jambalaya', 83),
('garlic mashed potatoes', 86),('roasted asparagus', 82),
('stuffed mushrooms', 84),('stuffed peppers', 82),
('chimichurri', 84),('harissa paste', 78),('pesto alla genovese', 88),
('mojito classic', 90),('pina colada', 88),('frozen margarita', 86),
('aperol spritz', 88),('mimosa champagne', 87),('virgin mojito', 84),
('caramel latte', 89),('vanilla latte', 90),('pumpkin spice latte', 91),
('peppermint mocha', 88),('oat milk latte', 88),
('chamomile tea', 85),('peppermint tea', 83),('ginger lemon tea', 80);
